networks:
  net:
    driver: bridge

include:
  - cart-service/deploy/local/docker-compose.yml
  - notification-service/deploy/local/docker-compose.yml
  - order-service/deploy/local/docker-compose.yml
  - product-service/deploy/local/docker-compose.yml

services:
  # Postgres database
  database:
    restart: "no"
    image: postgres:16-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8765:5432"
    networks:
      - net

  nats:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "--http_port 8222"
    networks: [ "net" ]
