apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: local
  labels:
    app: notification-service
    env: local
spec:
  selector:
    app: notification-service
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
