apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-init-sql
  namespace: local
data:
  create-cart-db.sql: |
    SELECT 'CREATE DATABASE cart'
    WHERE NOT EXISTS (SELECT
                      FROM pg_database
                      WHERE datname = 'cart')
    \gexec

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      volumes:
        - name: init-sql
          configMap:
            name: cart-init-sql
      initContainers:
        - name: init-db
          image: postgres:16
          command: [ "sh", "-c" ]
          args:
            - |
              echo "Waiting for PostgreSQL to be ready...";
              until pg_isready -h $(DATABASE_HOST) -U $(DATABASE_USERNAME); do
                sleep 2;
              done;
              echo "Running DB init script...";
              export PGPASSWORD=$DATABASE_PASSWORD;
              psql -h $(DATABASE_HOST) -U $(DATABASE_USERNAME) -f /sql/create-cart-db.sql postgres
          envFrom:
            - configMapRef:
                name: cart-service-config
            - secretRef:
                name: cart-service-secrets
          volumeMounts:
            - name: init-sql
              mountPath: /sql

      containers:
        - name: cart-service
          image: docker.io/cgayet/cart-service:0.0.1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: cart-service-config
            - secretRef:
                name: cart-service-secrets