networks:
  net:
    driver: bridge

services:
  cart-service:
    restart: "no"
    build:
      context: ../../.
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=database
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=cart_db
      - DATABASE_SSL=false
    ports:
      - "3001:3000"
    networks:
      - net
    depends_on:
      database:
        condition: service_healthy
