networks:
  net:
    driver: bridge

services:
  # Postgres database
  database:
    restart: "no"
    image: postgres:16-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8765:5432"
    networks:
      - net

  cart-service:
    restart: "no"
    image: docker.io/cgayet/cart-service:0.0.1
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=database
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=cart
      - DATABASE_SSL=false
    ports:
      - "3000:3000"
    networks:
      - net
    depends_on:
      database:
        condition: service_healthy
