networks:
  net:
    driver: bridge

services:
  notification-service:
    restart: "no"
    build:
      context: ../../.
    networks:
      - net
    depends_on:
      database:
        condition: service_healthy
