apiVersion: v1
kind: ConfigMap
metadata:
  name: products-init-sql
  namespace: local
data:
  create-products-db.sql: |
    SELECT 'CREATE DATABASE products'
    WHERE NOT EXISTS (SELECT
                      FROM pg_database
                      WHERE datname = 'products')
    \gexec

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service
  namespace: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-service
  template:
    metadata:
      labels:
        app: products-service
    spec:
      volumes:
        - name: init-sql
          configMap:
            name: products-init-sql
      initContainers:
        - name: init-db
          image: postgres:16
          command: [ "sh", "-c" ]
          args:
            - |
              echo "Waiting for PostgreSQL to be ready...";
              until pg_isready -h $(DATABASE_HOST) -U $(DATABASE_USERNAME); do
                sleep 2;
              done;
              echo "Running DB init script...";
              export PGPASSWORD=$DATABASE_PASSWORD;
              psql -h $(DATABASE_HOST) -U $(DATABASE_USERNAME) -f /sql/create-products-db.sql postgres
          envFrom:
            - configMapRef:
                name: products-service-config
            - secretRef:
                name: products-service-secrets
          volumeMounts:
            - name: init-sql
              mountPath: /sql

      containers:
        - name: products-service
          image: docker.io/cgayet/products-service:0.0.2
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: products-service-config
            - secretRef:
                name: products-service-secrets